apiVersion: v2
name: cf-tunnel-operator
description: this chart deploys cf-tunnel-operator. The operator manages the cloudflare app that automates and manages cloudflare tunnel and DNS entries.
version: 0.1.1
appVersion: v0.1.2
