image:
  repository: docker.io/rk90229/cf-tunnel-operator
  tag: main-40918d7
namespace: cf-tunnel-operator-system
credentialsSecret: cf-tunnel-operator-credentials
serviceAccount:
  name: cf-tunnel-operator
clusterrole:
  name: cf-tunnel-operator
resources:
  requests:
    cpu: 5m
    memory: 20Mi
  limits:
    cpu: 50m
    memory: 64Mi
securityContext: {}
